# Generated by Django 2.2.2 on 2019-06-22 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190621_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(help_text='Enter comment about blog here.', max_length=300),
        ),
    ]
