# Generated by Django 2.2.2 on 2019-06-22 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190622_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='post_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
