# Generated by Django 2.2.2 on 2019-06-22 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190622_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post_time',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
